### ISSUE TITLE
vendor.qti.hardware.radio.qtiradio duplicate line

### ISSUE THREAD

**Issue by TogoFire** [ArrowOS-Devices/android_device_xiaomi_trinket-common#1]
https://github.com/ArrowOS-Devices/android_device_xiaomi_trinket-common/blob/4c2a037760297eb0deca079120f2dbc336dd5e7b/configs/hidl/manifest.xml#L514

**Comment by danielml3** [comment]
This isn't a problem, may be needed for the different revisions of the interface.

**Comment by adithya2306** [comment]
https://source.codeaurora.org/quic/la/platform/vendor/qcom/trinket/tree/manifest.xml?h=LA.UM.8.11.r1-04800-NICOBAR.0#n401
what @daniml3 said above.
